### ISSUE TITLE
How do I access the information in rocket_snake.data_classes.RankedSeasons

### ISSUE THREAD

**Issue by gilgtc** [Drummersbrother/rocket-snake#5] opened 2017-08-09 20:02 UTC
Suppose rs is my RankedSeasons object, when I do rs.keys() it replies dict_keys(['5', '4', '2', '3']).

But when, for example, I do rs['2'] it gives me RecursionError, RecursionError: maximum recursion depth exceeded.

Any help would be appreciated.

**Comment by Drummersbrother** [comment] 2017-08-10 07:12
Thank you for reporting that bug, I will  try to reproduce and fix it later today 😊.

**Comment by Drummersbrother** [comment] 2017-08-10 16:51
Since there are both `RankedSeasons` and `RankedSeason` objects (admittedly not a good choice of names), and I could not reproduce your problem with `RankedSeasons` objects, I assume this is using the `RankedSeason` objects. 

I have pushed what I believe should fix your problem, and I will version bump the repo and push to pypi. I will close this issue if the new version fixes your issue.

**Comment by gilgtc** [comment] 2017-08-11 00:17
It seems to be working! Thanks for all your hard work!

**Comment by Drummersbrother** [comment] 2017-08-11 05:25
Nice! I'll close the issue then. (And thanks 😊)

**Closed as completed by Drummersbrother** 2017-08-11 05:25 UTC
